services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: tutortoise
      POSTGRES_PASSWORD: tutortoise
      POSTGRES_DB: tutortoise_test
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tutortoise -d tutortoise_test"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
