name: tutortoise
services:
  backend:
    ports:
      - 8080:8080
    build: .
    environment:
      - DATABASE_URL=
      - FIREBASE_SERVICE_ACCOUNT_KEY=
      - FIREBASE_DATABASE_URL=
      - GCS_BUCKET_NAME=
      - GOOGLE_OAUTH_CLIENT_ID=
      - JWT_SECRET=
    restart: on-failure:5
