name: tutortoise
services:
  backend:
    ports:
      - 8080:8080
    build: .
    environment:
      - FIREBASE_SERVICE_ACCOUNT_KEY=
      - FIREBASE_DATABASE_URL=
      - GCS_BUCKET_NAME=
      - GOOGLE_MAPS_API_KEY=
    restart: on-failure:5
