name: Deploy API Documentation

on:
  push:
    branches: [master]
    paths:
      - "src/**"
      - ".github/workflows/api-docs.yml"
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install

      - name: Generate Swagger documentation
        run: pnpm run swagger

      - name: Create documentation site
        run: |
          mkdir -p docs/api
          mv src/swagger/specs.json docs/api/
          cat > docs/api/index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <title>Tutortoise API Documentation</title>
            <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/5.11.8/swagger-ui.css">
            <style>
              body { margin: 0; }
              .swagger-ui .topbar { display: none; }
            </style>
          </head>
          <body>
            <div id="swagger-ui"></div>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/5.11.8/swagger-ui-bundle.js"></script>
            <script>
              window.onload = () => {
                window.ui = SwaggerUIBundle({
                  url: "./specs.json",
                  dom_id: "#swagger-ui",
                  deepLinking: true,
                  presets: [
                    SwaggerUIBundle.presets.apis,
                    SwaggerUIBundle.SwaggerUIStandalonePreset
                  ],
                });
              };
            </script>
          </body>
          </html>
          EOF

      - if: github.ref == 'refs/heads/master'
        run: |
          echo "Documentation built from master branch at $(date)" > docs/api/build-info.txt

      - if: github.event_name == 'pull_request'
        run: |
          echo "Documentation preview for PR #${{ github.event.pull_request.number }} built at $(date)" > docs/api/build-info.txt

      - name: Upload documentation artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-documentation-${{ github.sha }}
          path: docs/api
          retention-days: 5

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          force_orphan: true

      - name: Create Job Summary
        run: |
          echo "### 📚 API Documentation" >> $GITHUB_STEP_SUMMARY
          if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "The documentation has been deployed to GitHub Pages:" >> $GITHUB_STEP_SUMMARY
            echo "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/api/" >> $GITHUB_STEP_SUMMARY
          else
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "Preview the documentation locally:" >> $GITHUB_STEP_SUMMARY
            echo "1. Go to the Actions tab" >> $GITHUB_STEP_SUMMARY
            echo "2. Click on this workflow run" >> $GITHUB_STEP_SUMMARY
            echo "3. Scroll down to the Artifacts section" >> $GITHUB_STEP_SUMMARY
            echo "4. Download 'api-documentation-${{ github.sha }}'" >> $GITHUB_STEP_SUMMARY
            echo "5. Extract the zip file" >> $GITHUB_STEP_SUMMARY
            echo "6. Open index.html in your browser" >> $GITHUB_STEP_SUMMARY
          fi
