name: Lint and Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        version: 9
        run_install: true
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: "pnpm"

    - name: Cache Firebase Emulators
      uses: actions/cache@v4
      with:
        path: ~/.cache/firebase/emulators
        key: ${{ runner.os }}-firebase-emulators-${{ hashFiles('~/.cache/firebase/emulators/**') }}
        restore-keys: |
          ${{ runner.os }}-firebase-emulators-

    - name: Run Linting
      run: pnpm run lint

    - name: Run Tests
      run: |
        npm install -g firebase-tools
        pnpm run test
      env:
        FIREBASE_AUTH_EMULATOR_HOST: 127.0.0.1:9090
        FIRESTORE_EMULATOR_HOST: 127.0.0.1:9090
        FIREBASE_DATABASE_EMULATOR_HOST: 127.0.0.1:9000
        FIREBASE_STORAGE_EMULATOR_HOST: 127.0.0.1:9199
        GCS_BUCKET_NAME: tutortoise-test

    - name: Build Project
      run: pnpm run build
