name: Lint and Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        version: 9
        run_install: true
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: "pnpm"

    - uses: ikalnytskyi/action-setup-postgres@v7
      id: postgres

    - name: Run Linting
      run: pnpm run lint

    - name: Run Tests
      run: |
        pnpm run db:migrate
        pnpm run test
      env:
        FIREBASE_DATABASE_EMULATOR_HOST: 127.0.0.1:9000
        FIREBASE_STORAGE_EMULATOR_HOST: 127.0.0.1:9199
        GCS_BUCKET_NAME: tutortoise-test
        DATABASE_URL: ${{ steps.postgres.outputs.connection-uri }}
        JWT_SECRET: xyz

    - name: Build Project
      run: pnpm run build
