name: Lint and Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache Bun dependencies
      uses: actions/cache@v4
      with:
        path: ~/.bun/install/cache
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
        restore-keys: |
          ${{ runner.os }}-bun-

    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: 1.1.38

    - name: Install dependencies
      run: bun install

    - uses: ikalnytskyi/action-setup-postgres@v7
      id: postgres

    - name: Run Linting
      run: bun lint

    - name: Run Tests
      run: |
        bun db:migrate
        bun run test
      env:
        FIREBASE_DATABASE_EMULATOR_HOST: 127.0.0.1:9000
        FIREBASE_STORAGE_EMULATOR_HOST: 127.0.0.1:9199
        GCS_BUCKET_NAME: tutortoise-test
        DATABASE_URL: ${{ steps.postgres.outputs.connection-uri }}
        JWT_SECRET: xyz
